# Generated by Django 4.1.13 on 2026-01-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'account_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BemoTransactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_num', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bemo_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CryptoTransactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_num', models.CharField(blank=True, max_length=255, null=True)),
                ('currency_name', models.CharField(blank=True, max_length=50, null=True)),
                ('network_name', models.CharField(blank=True, max_length=50, null=True)),
                ('SYP_for_unit', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=255)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'crypto_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_goal_id', models.CharField(max_length=20)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=25)),
                ('ammount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gifts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MessagesToAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('photo', models.TextField(blank=True, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages_to_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderMoneyTransactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('city_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=255)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_money_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShamCashTransactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_num', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=255)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sham_cash_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SyriatelTransactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_num', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=255)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'syriatel_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_id', models.IntegerField(blank=True, null=True)),
                ('provider_type', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.IntegerField()),
                ('action_type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.CharField(max_length=25, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True)),
                ('player_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('referal_code', models.CharField(max_length=255, unique=True)),
                ('referal_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.IntegerField(default=0)),
                ('account_balance', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('ichancy_cookie', models.TextField(blank=True, null=True)),
                ('admin_telegram_id', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=10, null=True)),
                ('admin_chat_id', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_bot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('transactions_telegram_bot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_channels', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_groups', models.CharField(blank=True, max_length=255, null=True)),
                ('bot_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cookie_from_group_id', models.CharField(blank=True, max_length=255, null=True)),
                ('crypto_deposit_group', models.CharField(blank=True, max_length=255, null=True)),
                ('crypto_withdraw_group', models.CharField(blank=True, max_length=255, null=True)),
                ('bemo_deposit_group', models.CharField(blank=True, max_length=255, null=True)),
                ('bemo_withdraw_group', models.CharField(blank=True, max_length=255, null=True)),
                ('syriatel_deposit_group', models.CharField(blank=True, max_length=255, null=True)),
                ('syriatel_withdraw_group', models.CharField(blank=True, max_length=255, null=True)),
                ('shamcash_deposit_group', models.CharField(blank=True, max_length=255, null=True)),
                ('shamcash_withdraw_group', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'settings',
                'managed': True,
            },
        ),
    ]
